---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.app.namespace | default "web-ui" }}
  name: {{ .Values.app.name }}
  labels:
    env: {{ .Values.app.env }}
    name: {{ .Values.app.name }}
    type: {{ .Values.app.type }}
spec:
  selector:
    matchLabels:
      env: {{ .Values.app.env }}
      name: {{ .Values.app.name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 40%
  progressDeadlineSeconds: 300
  replicas: 1
  template:
    metadata:
      labels:
        env: {{ .Values.app.env }}
        name: {{ .Values.app.name }}
        type: {{ .Values.app.type }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.app.image_pull_policy }}
          {{- if .Values.app.port }}
          ports:
            - containerPort: {{ .Values.app.port }}
          {{- end }}
        {{- if (or (gt (.Values.app.mem_limit | default 0.0) 0.0) (gt (.Values.app.cpu_limit | default 0.0) 0.0)) }}
          resources:
            limits:
              {{- if (gt (.Values.app.cpu_limit | default 0.0) 0.0) }}
              cpu: {{.Values.app.cpu_limit}}m
              {{- end }}
              {{- if (gt (.Values.app.mem_limit | default 0.0) 0.0) }}
              memory: {{.Values.app.mem_limit}}Mi
              {{- end }}
            requests:
              {{- if (gt (.Values.app.cpu_required | default 0.0) 0.0) }}
              cpu: {{.Values.app.cpu_required}}m
              {{- end }}
              {{- if (gt (.Values.app.mem_required | default 0.0) 0.0) }}
              memory: {{.Values.app.mem_required}}Mi
              {{- end }}
        {{- end }}
      imagePullSecrets:
        - name: registry
      {{- if .Values.app.node_selectors }}
      nodeSelector: 
        {{- range $key, $val := .Values.app.node_selectors }}
        {{ $key }}: {{ $val }}
        {{- end}}
      {{- end}}